language: ruby
cache: bundler
sudo: false
rvm:
- 2.2
- 2.1
- 2.0
- ruby-head
- jruby-9.0.3.0
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.0.3.0
  exclude:
    - rvm: jruby-9.0.3.0
      env: TEST_SUITE=cucumber
env:
  matrix:
    - TEST_SUITE=test
    - TEST_SUITE=cucumber
before_script: bundle update
script: script/cibuild
notifications:
  irc:
    on_success: change
    on_failure: change
  email:
    on_success: never
    on_failure: never
