# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gran Maratón de Tertulias por la Paz
description: > # Objetivos de la maratón es hablar de temas apoyando la paz mundial que es la resolución de conflictos para que cohabitamos en armonía y felicidad en la creación.
  Habrá una multitud de temas y dar la oportunidad a las personas de que se sumen a las tertulias abiertas y que todos expresen su parecer.
  168 horas donde pueden entrar 10 personas simultáneamente e ir rotando para que todos puedan dar su opinión y seguir difundiendo esta iniciativa de paz.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pazmundial.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
gems: [github-pages, bourbon, neat]
